### PR TITLE
suggestion for updated PBPK model structure figure

### LINKED ISSUE #13: Error in PK-Sim_PBPK_generic_model_scheme: the splenic vein should drain into the portal vein
The splenic vein should drain into the portal vein and not in to the venous blood.
Same applies for the pancreatic vein (which is completely missing, see #10)
(It is correctly implemented in PK-Sim.)

Applies to:
images/PK-Sim_PBPK_generic_model_scheme.png

### PR DESCRIPTION
**Pull request by sfrechen**
fixes #13 
fixes #14

### CODE REVIEW

**Comment by sfrechen** [comment]
@TWendl @AndreDlm

**Comment by Yuri05** [comment]
nice picture! 2 remarks:
* to make it more consistent, I would set the style of the Gall Bladder similiar to Feces and Urine (smaller and coloured rectangle)
* with Feces/Urine/GallBladder explicitly shown now: I think we don't need those 3 "outflow" arrows anymore
grafik

**Comment by AndreDlm** [comment]
Additionally, "gallbladder" is written in one word, you may correct that
Nice picture!

**Review by Incei — COMMENTED** [review]
I really like it! 
The only minor thing is that we still don't have a clear connection between oral-**inhalation** of compounds and the lung compartment.  Although in the image to the left the brain is over-present (looking like a major PK organ), whereas there's no lung shown which becomes more and more a administration target for our drugs?
E.g we could shift the lung cmt on top above / next to the stomache? I added a very simplistic exampl
incl_lung
e

**Comment by Incei** [comment]
Now that i look at it again, there are also no kidneys shown in the left figure :)

**Comment by sfrechen** [comment]
> Now that i look at it again, there are also no kidneys shown in the left figure :)

I do not have the original figure of that. But I guess the kidney is hidden behind the intestine. That is how it would like if you open the body ;-)

**Comment by sfrechen** [comment]
> I really like it! The only minor thing is that we still don't have a clear connection between oral-**inhalation** of compounds and the lung compartment. Although in the image to the left the brain is over-present (looking like a major PK organ), whereas there's no lung shown which becomes more and more a administration target for our drugs? E.g we could shift the lung cmt on top above / next to the stomache? I added a very simplistic exampl incl_lung e

I think inhalation is not implemented as standard route. So, would leave it out.

**Comment by AndreDlm** [comment]
@PavelBal do you still have the original file of that figure?

**Comment by sfrechen** [comment]
> Additionally, "gallbladder" is written in one word, you may correct that Nice picture!

adressed

> nice picture! 2 remarks:
> 
> * to make it more consistent, I would set the style of the Gall Bladder similiar to Feces and Urine (smaller and coloured rectangle)
> * with Feces/Urine/GallBladder explicitly shown now: I think we don't need those 3 "outflow" arrows anymore
>   grafik

Gallblader adressed. I kept the outflow arrows. My understanding was that these arrows represent metabolism (as intestine, liver and kidney are the most prominent organs for metabolism). But we may modify. I attached the powerpoint for future adaptions.

**Review by Incei — APPROVED** [review]

**Comment by sfrechen** [comment]
> @PavelBal do you still have the original file of that figure?

Would really be helpful. Was kind of tricky to have connect the new image to the large transparent arrow.

**Comment by AndreDlm** [comment]
Maybe this file already helps. Found it in my mailbox...
[PhysiologyComp_alt.zip](https://github.com/Open-Systems-Pharmacology/Qualification-text-modules/files/7353543/PhysiologyComp_alt.zip)

Not a ppt file but svg

**Comment by PavelBal** [comment]
Do you still need the source? I only have an svg.

**Comment by Yuri05** [comment]
>I kept the outflow arrows. My understanding was that these arrows represent metabolism (as intestine, liver and kidney are the most prominent organs for metabolism). But we may modify. I attached the powerpoint for future adaptions.

Ok. I always thought they would represent elimination/excretion :)
Let's keep the arrows then. Maybe we should extend them with an enzyme icon or with "M", like below? 
But if it's clear without additional symbols - I'm fine with that.
grafik................grafik

**Comment by sfrechen** [comment]
> > I kept the outflow arrows. My understanding was that these arrows represent metabolism (as intestine, liver and kidney are the most prominent organs for metabolism). But we may modify. I attached the powerpoint for future adaptions.
> 
> Ok. I always thought they would represent elimination/excretion :) Let's keep the arrows then. Maybe we should extend them with an enzyme icon or with "M", like below? But if it's clear without additional symbols - I'm fine with that. grafik................grafik

I added "Met."

**Review by Yuri05 — APPROVED** [review]

**Pull request merged**
